document.addEventListener('DOMContentLoaded', async () => {
    /*********************************
     * 1. Initialize Firebase
     *********************************/
    const firebaseConfig = {
      apiKey: "AIzaSyBn7xE-jaEuixzyDROnbHrQo6-YtOR5LaU",
      authDomain: "amusement-park-4039d.firebaseapp.com",
      projectId: "amusement-park-4039d",
      storageBucket: "amusement-park-4039d.appspot.com",
      messagingSenderId: "625618396056",
      appId: "1:625618396056:web:ff2907be3a1958ed9041ed",
      measurementId: "G-6QHBHT0PPE"
    };
    firebase.initializeApp(firebaseConfig);
    const db = firebase.firestore();
    const defaultRidesData = [
        {
          name: "AQUAMAN: Power Wave",
          description: "Experience the powerful force of this aquatic attraction as you’re pulled back and forth, mimicking the mighty waves of the ocean.",
          imageUrl: "rideImages/Aquaman.png",
          lat: 32.75694774660049,
          lng: -97.06858634954958,
          minHeight: 48,
          duration: 80,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 4,
          taste: 1,
          sound: 4,
          smell: 1,
          sight: 3
        },
        {
          name: "BATMAN The Ride",
          description: "See what it’s like behind the mask on this 50-mph juggernaut as you star in your own GOTHAM adventure.",
          imageUrl: "rideImages/Batman.jpg",
          lat: 32.75867956518985,
          lng: -97.0665944558818,
          minHeight: 54,
          duration: 135,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 8,
          taste: 1,
          sound: 7,
          smell: 1,
          sight: 8
        },
        {
          name: "BATWING",
          description: "Here’s a ride fit for brave young batboys and batgirls, perfect for toddlers and young children seeking adventure.",
          imageUrl: "rideImages/Batwing.png",
          lat: 32.757562316535875,
          lng: -97.067054891455,
          minHeight: 48,
          duration: 105,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 3,
          taste: 1,
          sound: 2,
          smell: 1,
          sight: 3
        },
        {
          name: "Boomtown Depot",
          description: "Climb aboard our classic train for a scenic cruise around the park. Enjoy the novelty of traveling by authentic steam engine.",
          imageUrl: "rideImages/BoomtownDepot.jpg",
          lat: 32.75775980664769,
          lng: -97.06749839143542,
          minHeight: 0,
          duration: 480,
          wheelchair: true,
          serviceAnimal: true,
          pregnant: true,
          touch: 2,
          taste: 1,
          sound: 3,
          smell: 1,
          sight: 3
        },
        {
          name: "Boot Scootin'",
          description: "No spurs or lasso required for this gently ‘bucking’ ride, perfect for young riders. Enjoy the west without too much 'wild.'",
          imageUrl: "rideImages/BootScootin.jpg",
          lat: 32.757154197253314,
          lng: -97.0720959368577,
          minHeight: 36,
          duration: 105,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 3,
          taste: 1,
          sound: 3,
          smell: 1,
          sight: 3
        },
        {
          name: "Bugs Bunny Cloud Bouncer",
          description: "Soar to new heights with this gentle beginner drop tower ride for young thrill-seekers, offering soft, cushioned drops.",
          imageUrl: "rideImages/BugsBunnyCloud.jpg",
          lat: 32.75637875518429,
          lng: -97.06841704130149,
          minHeight: 42,
          duration: 60,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 3,
          taste: 1,
          sound: 3,
          smell: 1,
          sight: 3
        },
        {
          name: "CATWOMAN Whip",
          description: "Hold onto the whip’s handle as this GOTHAM ride spins you around at heights up to 68 feet, swirling and twirling unpredictably!",
          imageUrl: "rideImages/Catwoman.jpg",
          lat: 32.75726920754156,
          lng: -97.06628719155061,
          minHeight: 48,
          duration: 240,
          wheelchair: true,
          serviceAnimal: false,
          pregnant: false,
          touch: 7,
          taste: 1,
          sound: 7,
          smell: 1,
          sight: 7
        },
